---
# tasks file for mysql
# Load vars specific to Os Family.
- include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family != 'Debian'

- include_tasks: install_RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: install_Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: configure.yml
- include_tasks: service.yml
