- name: create file if it doesn't exist
  file: state=touch path=/var/www/html/index.html

- name: If hostname not there, then add it to index.html
  lineinfile:
    state: present
    dest: /var/www/html/index.html
    line: Hostname={{ ansible_hostname }}
 

